### ISSUE TITLE
Speed issue

### ISSUE THREAD

**Issue by allentran** [IndicoDataSolutions/finetune#146]
Looking at #107 there is a notebook reported order of 10k iterations per second on the GPU [see this notebook](https://colab.research.google.com/drive/1M0XAbGicO8-Vtn01Tw9UhCd4NCz43IiQ) I'm getting <10 iterations per second [see this notebook](https://colab.research.google.com/drive/1M0XAbGicO8-Vtn01Tw9UhCd4NCz43IiQ)

Any ideas of what is going on? I tried 0.3.1 but that didn't speed anything up.

**Comment by madisonmay** [comment]
Hi Allen,

Unfortunately I would expect something on the order of 10 documents per second, depending on hardware.  I've looked through the notebook but I'm not sure where you're seeing 10k iterations per second?  Maybe that was the output of the tokenizer back when we still ran the tokenization with tqdm enabled?

The most recent version should be 0.4.x -- the speed difference between that and 0.3.1 is probably minimal but it's the version that's up to date with the current iteration of the documentation.

The most significant variable to play with in order to increase the number of documents per second you can process is `max_length`.  If your documents are short, dropping this value to 256 or 128 will be beneficial, as portions of the transformer model are `O(max_length^2)`.

Sorry!  I wish finetune was that fast but in this case accuracy comes at the price of performance. 

--Madison

**Comment by allentran** [comment]
OK cool, order of 10 makes sense, no need to apologize, just making sure my EC2 environment wasn't messed up.

**Comment by madisonmay** [comment]
Glad I could help, happy hacking!
