### ISSUE TITLE
Validation fails with unsupervised pretraining

### ISSUE THREAD

**Issue by bgreen-litl** [IndicoDataSolutions/finetune#157]
**Describe the bug**

When I attempt to pretrain a model using unlabeled data, I get an error if I have 50 or more examples:

`ValueError: Cannot feed value of shape (2, 0) for Tensor 'Placeholder_3:0', which has shape '(?, 1)'`

I'm guessing this is related to validation:

    :param val_size: Validation set size as a percentage of all training data.  Validation will not be run by default if n_examples < 50.

**Minimum Reproducible Example**

It seems to be dataset independent, however this does the trick:

    from sklearn.datasets import fetch_20newsgroups
    dataset = fetch_20newsgroups()

    from finetune import Classifier
    model = Classifier()
    model.fit(dataset.data[:50])

Note that if I instead take the slice `dataset.data[:49]` training succeeds.

**Comment by madisonmay** [comment]
Hi @bgreen-litl,

This issue should be fixed in our latest release (0.5.0) -- and finetune should be substantially quicker to boot. Could you upgrade your finetune version and confirm that the issue is resolved?  When running things locally on my machine everything seems good to go.

You can update either by pulling the latest development branch or running:

```
pip install finetune --upgrade
```

**Comment by bgreen-litl** [comment]
@madisonmay Pulling down the latest development I no longer have this issue. Thanks.
