### ISSUE TITLE
Deploying .model files using Tensorflow.js ?

### ISSUE THREAD

**Issue by emtropyml** [IndicoDataSolutions/finetune#345]
**Is your feature request related to a problem? Please describe.**
Models are saved/loaded with .model extension using the finetune wrapper. But this format is not supported by tensorflow.js for deployment on the web interface. 

**Describe the solution you'd like**
Would be nice to have a function to load/save models in .h5 or other formats supported by tensorflow.js

**Describe alternatives you've considered**
Deploying the model without using GPUs, but this would result in high latency outputs.

**Additional context**
https://www.tensorflow.org/guide/saved_model#save_and_restore_models

**Comment by benleetownsend** [comment]
Thanks for the feature request. I unfortunately I do not think that this is something we will be working on anytime soon. The problem with this is that we have large amounts of pre-processing code (tokenizers etc) that would need to be ported into javascript and then maintained for this to be worth it.

The current way we suggest deploying finetune is server-side using the cached predict interface of finetune to cache the model and then use your python library of choice (something like flask) to wrap finetune in an api that can serve predictions.

**Comment by sujitsagar** [comment]
Hi @benleetownsend, Is it possible to export the model into **Tensorflow Saved Model** format instead of **.model** file?

**Comment by benleetownsend** [comment]
It would be easy enough to export models in this format. You can get the underlying estimator object and input formats as follows:
```
model = ...
estimator, hooks = model.get_estimator()
(xtypes, ytypes), (xshapes, yshapes) = model.input_pipeline.feed_shape_type_def()
```

With this you should be able to follow https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator#export_saved_model to get the export. You may need to modify _get_estimator_config to re-enable the default estimator savers, i'm not sure the details of where the weights come from for the export.

I'm concerned however that there is some misconception as to what this might allow you to do. The Tensorflow Saved Model format exports only the model graph and weights.

Finetune contains a significant amount of python code (not in the graph) eg, tokenisers, input pipelines, output processing etc that means the underlying models, not in the finetune infrastructure, become difficult to make use of without significant work on porting the bits of finetune into the new infrastructure. Because of this, it is likely going to be simplest to integrate finetune into your work, rather than trying to pull the models out of finetune.

If you can give some more insight into what you are trying to achieve I can hopefully give some more guidance.

**Comment by sujitsagar** [comment]
@benleetownsend Thank you for your inputs.
We are looking for a solution to deploy generated model on to Google Cloud AutoML or AWS SageMaker

**Comment by madisonmay** [comment]
As there's no plan for tensorflow.js support near term I'm going to close this issue for now.
