### ISSUE TITLE
How to deploy finetune models in production?

### ISSUE THREAD

**Issue by emtropyml** [IndicoDataSolutions/finetune#392]

**Comment by madisonmay** [comment]
Hard for us to give too much general advice here, since every "production" scenario has different requirements in terms of memory, latency, throughput, etc... and those all factor into how you might want to structure finetune model deployment.  

In most scenarios I would just put the finetune model behind a little HTTP server (Flask, Django, Tornado, whatever your heart desires), and write a route like the following:

```
# Load model into memory ahead of time
MODEL = Classifier.load(model_path)

# Prevent graph re-compilation on each call to `model.predict()`
MODEL._cached_predict = True 

def predict(data):
    model.predict(data)
```

The only real gotcha here is the `_cached_predict` setting -- this needs to be set to True to prevent re-compiling the graph when each new example / batch of examples is sent to the model.

**Comment by madisonmay** [comment]
I don't think there's anything preventing you from using an interface like tensorflow serving since finetune uses the tensorflow estimator API behind the scenes, but you'd need to pull down the repo from source and find the right location to serialize the model / input pipeline out to a format that tensorflow serving accepts.  We don't use tensorflow serving ourselves at indico so don't have much experience there.

**Comment by sujitsagar** [comment]
Thank you for help @madisonmay. Is it possible to deploy the model file generated to Amazon SageMaker or Google Cloud AI Hub?

Can you recommend any other services which provide hosting these models on Demand? We cant keep our GPU servers constantly running because of cost constraint.

**Comment by madisonmay** [comment]
@sujitsagar It's unfortunately difficult as things are currently configured.  If you're moving to productionalization my recommendation would be to put this behind a tiny flask / django / tornado server.
