### ISSUE TITLE
max length for MultiLabelClassifier

### ISSUE THREAD

**Issue by rnyak** [IndicoDataSolutions/finetune#409]
**Describe the bug**

This is not a bug. More like a question. Can't we use max_length > 512 while training a MultiLabelClassifier? I am getting the error below after running this command line:

```
model = MultiLabelClassifier(n_epochs=2, val_size = 100, max_length= 1024, chunk_long_sequences=False)
model.fit(trainX, trainY)
```
`ValueError: Max Length cannot be greater than 512 if interpolate_pos_embed is turned off`

In addition, can we set the base model like in the example below?:

```model = MultiLabelClassifier(n_epochs=2, base_model=GPT2Model, ..) ```

**Minimum Reproducible Example**

**Expected behavior**

**Additional context**

**Comment by benleetownsend** [comment]
So the root of this is because most of our base models were trained with a maximum length of 512. We use the chunk_long_sequences heuristic to overcome this and find it works reasonably in practice, the basis of this is to take overlapping subsequences of text and then train and predict on chunks independently and then aggregate the predictions. You have this turned off so this will not be done.

The model labelled as `GPT2Model` is actually GPT2 Small which is why you still have the 512 restriction. 

The three things you can do to use a longer sequence length is this:
* Use one of the base models trained with a longer sequence length `BERTLarge`, `ROBERTALarge`, `GPT2Model345` or `GPT2Model762`. There is a very good chance these are just too big to be useful. `low_memory_mode=True` flag will help a lot with this.
* Use `chunk_long_sequences=True`. This heuristic described above has mixed results depending on the task but it is worth a try.
* Try `interpolate_pos_embed=True` This takes the positional embedding values and interpolates them to stretch them out to the new length. There is no theoretical underpinning for this that I am aware of, but in practice I have seen success with this and GPT, but have seen it to be damaging on BERT. Certainly worth a try particularly if you have a dataset on the larger side or if you know there are very long term dependencies in the data that chunking will destroy.

`model = MultiLabelClassifier(n_epochs=2, base_model=GPT2Model, ..)` would be the correct way to select the GPT2Model base model.

Very interested to hear how you get on and which solution you find works best for your usecase

**Comment by rnyak** [comment]
Thanks. Will try and see.

**Comment by benleetownsend** [comment]
Closing for now, let me know if you need any more help.
